---
title: Outline for talk
---

# Abstract

To build a sustainable consulting practice, I think you need a genuine value-add to the wider community. I am not convinced writing a post such as "10 things you need to do now to improve your data visualisations" cuts it. Teaching does. And more, I think you should share your course materials for free.

In this talk I will argue teaching and openly sharing your materials is a sustainable business model. The value learners pay for when they attend a course is not the slides or the code, those should be freely available online. The value they get, which they are paying for, is time with the instructor, and the commitment they make to carving out space to learn something new.

Developing free and open content compounds over time. It creates a living document you can refer to and update. It demonstrates your expertise not by telling people you know things, but by showing them. It surfaces your work to learners who would never have found you otherwise, and those learners become the pipeline for future consulting and collaboration. It also deepens your own understanding of the topic. So, you get professional development built in.

I will discuss a case study in R training: _Quarto for Scientists_ to illustrate how this works in practice. I hope to leave attendees with the conviction that creating useful, openly available learning content is not a distraction from building a consulting practice, but is a highly effective way to build, and sustain one.

## Key points

- **Time** is higher value than content
- Your course should demonstrate:
  - The ideas are important and worthwhile to learn
  - It is possible to learn it
- Short course teaching materials should be online and free
- The online materials continue to support that learning

## Audience poll

- Who teaches: 1/2 day, 1 day, 2-3 days course semester, etc
- Who teaches short courses?
- Whose material is online for free?

## My audience

- Those who develop **short course materials**.
- Anything from a 1 hour workshop to a 3 day course.
- Not "accredited courses": e.g., CPR, actuarials, etc.

## Key points

- **Time** is higher value than content
- Your course should demonstrate:
  - The ideas are important and worthwhile to learn
  - It is possible to learn it
- Short course teaching materials should be online and free
- The online materials continue to support that learning

## **Time** is higher value than content

- We can learn almost anything now
- The learner carves out time: protects it from emails, other distractions
- The learner gets YOUR time as the teacher
- They get to ask an expert, clarify misunderstandings
  - stop you and go: "Hey, how did you do that"
  
## Time: Watching an experienced user

- Contents do not substitute watching someone work

## Course ideas are important and worthwhile

> think the two most important messages that people can get from a short course are:

> a) the material is important and worthwhile to learn (even if it's challenging), and 
> b) it's possible to learn it!

-- Hadley Wickham - [from a github gist in 2015](https://gist.github.com/hadley/37c8078eb9d46b5dac7e)

## Ideas so far:

- Your course has enticed people to attend
- You convince them the ideas are worthwhile learning, and that they can learn them


## Short course teaching materials should be online and free

- Your slides
- Written notes
- Text books (that you have written)
- Quiz questions/answers

:::{.notes}
This is essentially an extension of ideas that I have seen from peers in my community. There is a growing movement to make your textbooks free and available online.
:::

  - Yihui Xie: ["write a book with Chapman & Hall"](https://yihui.org/en/2018/08/bookdown-crc/)
  - Jenny Bryan: ["happygitwithr"](https://happygitwithr.com/), [What They Forgot to Teach You About R](https://rstats.wtf/), ["stat545"](https://stat545.com/)
  - Hadley Wickham: ["Advanced R"](https://adv-r.hadley.nz/), ["Mastering Shiny"](https://mastering-shiny.org/), ["R Packages"](https://r-pkgs.org/)
  - [Rob Hyndman]()
  - Miles McBain: [git for scientists](https://milesmcbain.github.io/git_4_sci/)
  - ["Introduction to Statistical Learning"]()
  - []()
  
## I'm not saying: "Deliver your courses for free"

## What I am saying: give people an option

- If they want to put in the extra work, use your materials as a resource, to learn the thing, great
- If they want to see you "in person" (or on screen?), then they can pay for that
- But putting the course material up online kind of only really serves to help you

## A recipe for a course

(Demo training.njtierney.com?)

- Make a bookdown/quarto book
- Add an appropriate license [CC BY-NC-4.0](https://creativecommons.org/licenses/by-nc/4.0/)
  - You can share/adapt
  - You must attribute
  - You cannot use the material for commercial purposes

- Put it on github
- Have it render when you make changes
- Deliver the course in-person, or online
- You don't need to share "course notes" or slides with your students
- They just get everything from the online book
- And after the 


## This has been happening for some time

- edX, MOOC (MOORPGs)
- Youtube
- Harvard's CS101
- MIT's Linear Algebra course


## Example: qmd4sci

- github repo: [njtierney/qmd4sci](https://github.com/njtierney/qmd4sci)
- exercises: [njtierney/qmd4sci-materials](https://github.com/njtierney/qmd4sci-materials)
- website: [qmd4sci.njtierney.com](https://qmd4sci.njtierney.com)

## What isn't included?

- Videos of your courses where you are teaching the content
- I see this mostly as a problem where your students should feel like they can ask any question and not be criticised/seen online. 

My reasons here are:

- People don't pay for courses to get content. They pay for your time. Put differently: The most valuable thing users get out of teaching is face to face (zoom to screen?) time. The content continues to become an ongoing, useful idea.

- If students/users are given a packet of slides or teaching materials, then if they return to them in the following weeks/months/years, then are they really going to be kept up to date?
- How do you find your teaching materials again? Is it in an email? What if you don't have access to that email address again?
- Make your teaching material accessible - put it on github, on your website, on zenodo. Put it online.
- Congratulations, your teaching resource has now transformed into 

## I don't think this is new


- The value people derive isn't from the content itself
- The value people yield is **time** - theirs, and yours
  - Their time, carved out, to take your course
  - Your time, they get to see you operate, ask you questions
- Your course should show them:
  - The ideas are important and worthwhle to learn
  - It is possible to learn it


## Hadley's quote

> think the two most important messages that people can get from a short course are:

> a) the material is important and worthwhile to learn (even if it's challenging), and 
> b) it's possible to learn it!

-- Hadley Wickham - https://gist.github.com/hadley/37c8078eb9d46b5dac7e

## Dave Borg


One of the most useful things in a workshop is seeing the process - it convvinces you that the thing is worth learning. 

these workshops help improve your  mental model - which allows you to improve how you learn a thing, as you have more nodes.

how much time are you affording to sit down and solve things - your coding resilience.


## In the R community

## How this is different for university courses

- Universities might not want your teaching content online for free - copyright can be challenging here
- The learning at a university course happens consistently over a time period of like 13 weeks. You are practicing the skills in that time. Of course, it would still be useful if the materials are always there and easy to find.
- Mostly you are then practicing using the skills during the university semester.
- However, a short course often follows a pattern of a student taking time off to learn the material, then they might not have a direct opportunity to 


## Things that can be only for those that pay

- Video recording of the course. Captures their experience
- Turn your course into a book - keep the online version free, make the hard copy have a cost.


## The story?

-


## Sustainable consulting

- We need to put our knowledge back out into the community
- Not a LinkedIn™ post: 
  - "The 10 types of clustering that all data scientists need to know. Let's dive in:"
- Not a "free webinar"
- Your teaching materials
- Online, free. Forever.

:::{.notes}
- Why do we "need" to give back?
- Why is this sustainable?
:::

## What do you mean, "free"?

- I mean "free as in beer"

## But why would people pay for "free" teaching materials

- Given enough time, people can learn what they want.
- The key component is "time".
- Time with the instructor.
- Time they have carved out to learn something new.

## Benefits of free course materials

- Compounds over time
- A living document that can be updated freely
- Deepens your own understanding of the topic
- Demonstrates your expertise - show people what you know
  - This is "Free advertising".
  
## This is not "my idea"

This is essentially an extension of ideas that I have seen from peers in my community. There is a growing movement to make your textbooks free and available online.

  - Yihui Xie: ["write a book with Chapman & Hall"](https://yihui.org/en/2018/08/bookdown-crc/)
  - Jenny Bryan: ["happygitwithr"](https://happygitwithr.com/), [What They Forgot to Teach You About R](https://rstats.wtf/), ["stat545"](https://stat545.com/)
  - Hadley Wickham: ["Advanced R"](https://adv-r.hadley.nz/), ["Mastering Shiny"](https://mastering-shiny.org/), ["R Packages"](https://r-pkgs.org/)
  - [Rob Hyndman]()
  - Miles McBain: [git for scientists](https://milesmcbain.github.io/git_4_sci/)
  - ["Introduction to Statistical Learning"]()
  - []()
  
More recently

## Other core ideas

- Courses aren't a primary product/source of income
- Teaching courses is a way to get people in front of you
- 


## Case study: Quarto for Scientists

- Built upon "Rmarkdown for scientists"
- [11 contributions from external people - I did not request or ask for this help](https://github.com/njtierney/rmd4sci/pulls?q=is%3Apr+is%3Aclosed+-author%3Anjtierney+)
- rmd4sci: 127 stars on github
- qmd4sci: 67 stars on github
- 

## It's "free advertising"

- And, yes, you better bet I'm taking this chance to advertise my teaching material
- In fact, I'm advertising my training.njtierney.com courses!

:::{.notes}
I will discuss a case study in R training: _Quarto for Scientists_ to illustrate how this works in practice. 
:::

:::{.notes}
I hope to leave attendees with the conviction that creating useful, openly available learning content is not a distraction from building a consulting practice, but is a highly effective way to build, and sustain one.
:::

## Can you make some parts "not free"

- I think there is a case for the following to be made 'paid':
  - Online recordings of the course material
  - Video content of the course
